<a href="https://colab.research.google.com/github/jhuee/DeepLearning/blob/main/batchNorm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [5]:
X = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

print(X.shape)
print(X)

torch.Size([3, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [6]:
bn = nn.BatchNorm1d(3)
output_bn = bn(X)
print(output_bn)


tensor([[-1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247]], grad_fn=<NativeBatchNormBackward0>)


In [7]:
#직접 구현
def batch_norm(X, eps = 1e-5):
  mean = X.mean(dim=0, keepdim=True)
  var = X.var(dim=0, unbiased=False, keepdim=True)
  X_norm = (X - mean) / torch.sqrt(var + eps)
  return X_norm

print(batch_norm(X))

tensor([[-1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247]])
