<a href="https://colab.research.google.com/github/jhuee/DeepLearning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np

In [11]:
a = [[1,2],[3,4]]

In [12]:
x_data = torch.tensor(a)

In [13]:
x_data

tensor([[1, 2],
        [3, 4]])

In [14]:
  b = np.array(a)

In [15]:
torch.tensor(b)

tensor([[1, 2],
        [3, 4]])

In [16]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [17]:
x_data.shape
x_data.dtype
x_data.device

device(type='cpu')

In [19]:
torch.cuda.is_available()

False

In [20]:
x_Data.to('cuda') #GPU로 보내고 싶을 때

NameError: name 'x_Data' is not defined

In [21]:
#.T는 transpose
#문법이 numpy랑 비슷한 게 많다.

In [26]:
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda
import matplotlib.pyplot as plt

In [28]:
training_data = datasets.FashionMNIST( root = 'data', train = True, download = True, transform = ToTensor())

100%|██████████| 26421880/26421880 [00:01<00:00, 18779811.77it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 348720.93it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 6161421.24it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 17844857.02it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [29]:
test_data = datasets.FashionMNIST( root = 'data', train = False, download = True, transform = ToTensor())

In [ ]:
#annotiationfile : label이 붙은 파일
#무조건 해야한 것, init, len, getitem(index) 이 세개를 오버라이드 해줘야 로컬에서 사용 가능하다.
#x는 학습데이터, y는 라벨을 로드를 하고 코드를 짜주면 된다
#그 다음에 Dataloader에 넣어준다.


# Dataloader의 역할
1. batch
  - 배치로 잘라주는 역할을 dataloader가 하며 한 바퀴 도는 게 1 epoch
2. shuffling
  - 순서도 외우기 때문에 순서도 섞어준다. 1epoch 돌 때마다 셔플 돌리기
  - test 할 때는 별로 상관 없음


# Define the Class
  1. init로 레이어 정의해주기
    - nn.Module로 ?
    - 선형 -> Relu -> 선형으로 레이어를 쌓아 올린다.
  2. foward
    - slef, x를 입력값으로 받는다.
    - 입력이 들어오면 어떤 레이어를 거쳐 값이 나오는지 foward한다.
    - 다음주 구현

# loss_fn
 상속 받지 않고 직접 구현해도 됨


# Optimizer
1. torch.optim.SGD로 SGD 쓰기
2. 혹은 torch.optim.ADAM
3. ADAM이나 ADAMW일 경우 lr = le^{-3}


# 학습 방법
1. dataloader를 for문에 넣으면 모델에 X를 넣게 되면 f(X)가 나온다.
2. Loss에 대한 미분값 계산 -> Backpropagation
  - zero로 비워주기
  - loss backward
  - 미분값 계산

1~2가 1epoch

3. batch%100
  - loss 가 줄어드고 있는지 확인

#Save and Loading Models
1. torch.save하고
2. torch.load
아키텍처가 같이 저장 돼서 용량이 큼

1. torch.salve(model.state_dict(), 'model_weights.pth')
-> 용량 작게, 아키텍처 버림